//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessStreamline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestellung
    {
        public int BestellungId { get; set; }
        public Nullable<System.DateTime> ErstelltAm { get; set; }
        public int NachfrageId { get; set; }
        public int AngebotId { get; set; }
    
        public virtual Angebot Angebot { get; set; }
        public virtual Nachfrage Nachfrage { get; set; }
    }
}
