//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessStreamline.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusinessStreamlineEntities : DbContext
    {
        public BusinessStreamlineEntities()
            : base("name=BusinessStreamlineEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anbieter> Anbieter { get; set; }
        public virtual DbSet<Angebot> Angebot { get; set; }
        public virtual DbSet<Bestellung> Bestellung { get; set; }
        public virtual DbSet<Firma> Firma { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Nachfrage> Nachfrage { get; set; }
        public virtual DbSet<Produkt> Produkt { get; set; }
        public virtual DbSet<Teil> Teil { get; set; }
        public virtual DbSet<Typ> Typ { get; set; }
        public virtual DbSet<ViewOffeneNachfrage> ViewOffeneNachfrage { get; set; }
        public virtual DbSet<ViewSucheNachfrage> ViewSucheNachfrage { get; set; }
        public virtual DbSet<ViewTeil> ViewTeil { get; set; }
        public virtual DbSet<ViewAngebotBesterPreisNachfrage> ViewAngebotBesterPreisNachfrage { get; set; }
        public virtual DbSet<ViewAnzahlAngeboteNachfrage> ViewAnzahlAngeboteNachfrage { get; set; }
        public virtual DbSet<ViewAngebot> ViewAngebot { get; set; }
        public virtual DbSet<ViewNachfrage> ViewNachfrage { get; set; }
        public virtual DbSet<ViewNachfrageBestellung> ViewNachfrageBestellung { get; set; }
    }
}
