
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BusinessStreamline.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Firma
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Firma()
    {

        this.Produkt = new HashSet<Produkt>();

    }


    public int FirmaId { get; set; }

    public int LoginId { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Produkt> Produkt { get; set; }

    public virtual Login Login { get; set; }

}

}
