
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BusinessStreamline.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Produkt
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Produkt()
    {

        this.Teil = new HashSet<Teil>();

    }


    public int ProduktId { get; set; }

    public string Name { get; set; }

    public int FirmaId { get; set; }



    public virtual Firma Firma { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Teil> Teil { get; set; }

}

}
