//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessStreamline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewBestellung
    {
        public int AngebotId { get; set; }
        public decimal PreisProTeil { get; set; }
        public string TeilName { get; set; }
        public int ProduktId { get; set; }
        public string ProduktName { get; set; }
        public string AnbieterName { get; set; }
        public string FirmaName { get; set; }
        public System.DateTime BestellDatum { get; set; }
        public int FirmaLoginId { get; set; }
        public int AnbieterLoginId { get; set; }
        public int NachfrageId { get; set; }
        public int FirmaId { get; set; }
        public int BestellungId { get; set; }
        public int AnbieterId { get; set; }
        public int QualitaetId { get; set; }
        public string TeilQualitaetName { get; set; }
        public System.DateTime Liefertermin { get; set; }
    }
}
