//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessStreamline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewNachfrage
    {
        public int NachfrageId { get; set; }
        public int Anzahl { get; set; }
        public System.DateTime ErstelltAm { get; set; }
        public Nullable<int> AnzahlAngebote { get; set; }
        public Nullable<decimal> BesterPreis { get; set; }
        public Nullable<bool> IstOffen { get; set; }
        public int ProduktId { get; set; }
        public string ProduktName { get; set; }
        public string TeilName { get; set; }
        public int FirmaId { get; set; }
        public int LoginId { get; set; }
    }
}
