//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessStreamline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAngebotBesterPreisNachfrage
    {
        public int NachfrageId { get; set; }
        public Nullable<decimal> BesterPreis { get; set; }
        public int AngebotId { get; set; }
    }
}
