//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessStreamline.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTeil
    {
        public int TeilId { get; set; }
        public string TeilName { get; set; }
        public Nullable<int> Anzahl { get; set; }
        public int TypId { get; set; }
        public string TypName { get; set; }
        public int ProduktId { get; set; }
        public string ProduktName { get; set; }
        public Nullable<bool> HatOffeneNachfrage { get; set; }
        public Nullable<int> OffeneNachfrageId { get; set; }
    }
}
